# Docker Compose Configuration for Shared Qdrant Instance
# Simplified shared architecture - single Qdrant container for all projects
# Project isolation achieved through collection namespacing

services:
  qdrant:
    container_name: "heimdall-shared-qdrant"
    image: qdrant/qdrant:v1.14.1
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - heimdall-shared-data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:6333/ || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - heimdall-network

volumes:
  heimdall-shared-data:
    name: "heimdall-shared-data"
    driver: local

networks:
  heimdall-network:
    name: "heimdall-shared-network"
    driver: bridge
