name: Release Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      test_upload:
        description: 'Upload to TestPyPI instead of PyPI'
        required: false
        default: false
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine typer rich

    - name: Install package dependencies
      run: |
        pip install -e .

    - name: Run release script (build and check)
      run: |
        python scripts/release.py --no-upload

    - name: Upload to TestPyPI
      if: ${{ github.event.inputs.test_upload == 'true' }}
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        python -m twine upload --repository testpypi dist/*

    - name: Upload to PyPI
      if: ${{ github.event_name == 'release' && github.event.inputs.test_upload != 'true' }}
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m twine upload dist/*

    - name: Create release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-packages
        path: dist/
